In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
import numpy as np
import argparse
from imutils import paths
import cv2

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
#out is the folder that will contain the augmented images
datapath="/content/drive/My Drive/Non-cleft"
out="/content/drive/My Drive/augimages/target"

In [ ]:
print("[INFO] loading images...")
imagePaths = list(paths.list_images(datapath))
print(imagePaths)
data=[]

[INFO] loading images...
['/content/drive/My Drive/Non-cleft/nc1.jpg', '/content/drive/My Drive/Non-cleft/nc2.jpg', '/content/drive/My Drive/Non-cleft/nc3.png', '/content/drive/My Drive/Non-cleft/nc4.jpg', '/content/drive/My Drive/Non-cleft/nc5.jpg', '/content/drive/My Drive/Non-cleft/nc6.png', '/content/drive/My Drive/Non-cleft/nc7.jpg', '/content/drive/My Drive/Non-cleft/nc8.png', '/content/drive/My Drive/Non-cleft/nc9.jpg', '/content/drive/My Drive/Non-cleft/nc10.png', '/content/drive/My Drive/Non-cleft/nc11.png', '/content/drive/My Drive/Non-cleft/nc12.png', '/content/drive/My Drive/Non-cleft/nc13.png', '/content/drive/My Drive/Non-cleft/nc14.png', '/content/drive/My Drive/Non-cleft/nc15.png', '/content/drive/My Drive/Non-cleft/nc16.png', '/content/drive/My Drive/Non-cleft/nc17.png', '/content/drive/My Drive/Non-cleft/nc18.jpg', '/content/drive/My Drive/Non-cleft/10.jpeg', '/content/drive/My Drive/Non-cleft/11.jpeg', '/content/drive/My Drive/Non-cleft/12.jpeg', '/content/drive/My D

In [ ]:
#resize the images and convert color to RGB and put it in datanp array to use it
for imagePath in imagePaths:
    print(imagePath)
    image = cv2.imread(imagePath)
	  #cv2.imshow(image)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    print(image)
    print("////////////////////////")
    image = img_to_array(image)
    print(image)
    image = np.expand_dims(image, axis=0)
    data.append(image)
datanp=np.array(data)

/content/drive/My Drive/Non-cleft/nc1.jpg
[[[ 74  38   6]
  [ 73  37   5]
  [ 73  37   5]
  ...
  [106  74  22]
  [ 94  62  14]
  [105  73  27]]

 [[ 73  37   5]
  [ 74  38   6]
  [ 74  38   6]
  ...
  [113  81  28]
  [ 93  62  12]
  [ 95  65  18]]

 [[ 74  39   6]
  [ 73  37   5]
  [ 72  36   4]
  ...
  [118  87  33]
  [102  72  19]
  [ 89  59   9]]

 ...

 [[224 216 203]
  [223 215 202]
  [224 216 203]
  ...
  [205 201 189]
  [207 203 191]
  [208 204 192]]

 [[223 216 202]
  [223 215 202]
  [223 215 202]
  ...
  [203 199 187]
  [206 202 190]
  [208 204 192]]

 [[223 215 202]
  [222 214 201]
  [222 214 201]
  ...
  [200 196 184]
  [204 200 189]
  [207 203 192]]]
////////////////////////
[[[ 74.  38.   6.]
  [ 73.  37.   5.]
  [ 73.  37.   5.]
  ...
  [106.  74.  22.]
  [ 94.  62.  14.]
  [105.  73.  27.]]

 [[ 73.  37.   5.]
  [ 74.  38.   6.]
  [ 74.  38.   6.]
  ...
  [113.  81.  28.]
  [ 93.  62.  12.]
  [ 95.  65.  18.]]

 [[ 74.  39.   6.]
  [ 73.  37.   5.]
  [ 72.  36.   4.]
  

In [ ]:
# ImageDataGenerator class ensures that the model receives new variations of the images
print(len(datanp))
aug = ImageDataGenerator(
	rotation_range=30,
	zoom_range=0.15,
	width_shift_range=0.2,
	height_shift_range=0.2,
	shear_range=0.15,
	horizontal_flip=True,
	fill_mode="nearest")
total = 0
imageGen=[]

49


In [ ]:
# apply image augmentation on the images
print("[INFO] generating images...")

for i in range(len(datanp)):
  print("Generating is running")
  imageGen = aug.flow(datanp[i], batch_size=1,save_to_dir=out, save_prefix="image", save_format="jpg")
  for image in imageGen:
    total+=1
    if (total % 6 == 0):
      break

[INFO] generating images...
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Generating is running
Gene